"""empty message

Revision ID: 96b3130e3099
Revises: afde866eb9ef
Create Date: 2024-07-31 21:23:41.766050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b3130e3099'
down_revision = 'afde866eb9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=80), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=80), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
